# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GalleryImagesUploadSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryImagesUploadSwift

  pod 'Alamofire'
  pod 'ESPullToRefresh'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'GBHFacebookImagePicker'
  
  target 'GalleryImagesUploadSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
